export const TOURDATA = [
    {
        id: '1',
        name: 'Best of Paris in 7 Days Tour',
        info: "Paris is the capital of France, one of Europe's largest cities, and one of the most populous cities in the European Union. It is the largest city proper of the Île-de-France, a region of France that includes the Île-de-France metropolitan region and several other regions...",
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$100',
    },
    {
        id: '2',
        name: 'Best Ireland in 14 Days Tour',
        info: 'Ireland is a country in the continent of Europe. It is the largest country in the European Union and the second-largest in the European Union after France. The country is situated in the North Atlantic Ocean, at the mouth of the River Liffey. The country is bordered to the north by the English Channel and to the south by the North Sea and the Bretonnia...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$200',
    },
    {
        id: '3',
        name: 'Best of London in 7 Days Tour',
        info: 'London is the capital and most populous city of England and the United Kingdom. Standing on the River Thames in the south-east of the island of Great Britain, London has been a major settlement for two millennia, its history going back to its founding by the Romans, who named it Londinium. London is the most populous city in the European Union...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$300',
    },
    {
        id: '4',
        name: 'Best of Madrid in 7 Days Tour',
        info: 'Madrid is the capital and largest city of Spain. It is located in the central region of the country, in the province of Murcia. The city is the most populous city in Spain and the second most populous in the European Union after London. The city is the centre of the Madrid metropolitan area, the second largest in the European Union...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$400',
    },
    {
        id: '5',
        name: 'Best of Barcelona in 7 Days Tour',
        info: 'Barcelona is the capital and largest city of Catalonia, the second most populous city in Spain after Madrid, and the seventh most populous city in the European Union after Paris. The city is located in the south-west of Spain, in the Catalonia region. The city is the centre of the Catalonia metropolitan area, the second largest in the European Union...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$500',
    },
    {
        id: '6',
        name: 'Best of Rome in 7 Days Tour',
        info: 'Rome is the capital and largest city of Italy. It is located in the centre of the Italian Peninsula, in the Lazio region. The city is the most populous city in Italy and the fourth most populous in the European Union after London, Berlin, and Rome. The city is the centre of the Lazio metropolitan area, the second largest in the European Union...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$600',
    },
    {
        id: '7',
        name: 'Best of Prague in 7 Days Tour',
        info: 'Prague is the capital and largest city of the Czech Republic. It is located in the central region of the country, in the region of the Bohemian Revolution. The city is the most populous city in the Czech Republic and the third most populous in the European Union after Berlin and Paris. The city is the centre of the Prague metropolitan area, the second largest in the European Union...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$700',
    },
    {
        id: '8',
        name: 'Best of Berlin in 7 Days Tour',
        info: 'Berlin is the capital and largest city of Germany. It is located in the central region of Germany, in the Berlin region. The city is the most populous city in Germany and the third most populous in the European Union after London and Paris. The city is the centre of the Berlin metropolitan area, the second largest in the European Union...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$800',
    },
    {
        id: '9',
        name: 'Best of New York in 7 Days Tour',
        info: 'New York is the state capital of the United States and the most populous city in the United States. With an estimated 2018 population of 8,398,467, New York is the third most populous city in the United States after Washington, D.C. and Chicago. New York is the most populous city in the United States...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$900',
    },
    {
        id: '10',
        name: 'Best of Tokyo in 7 Days Tour',
        info: 'Tokyo is the capital of Japan. It is the center of the Greater Tokyo Area, and the most populous metropolitan area in the world. The Greater Tokyo Area is the most populous metropolitan area in the world. The Greater Tokyo Area is the most populous metropolitan area in the world...',
        image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',
        price: '$1000',
    },
]
