export const MENULIST = [
    {
        id: 1,
        title: 'Blueberry Cheesecake',
        category: 'Dessert',
        price: '$2.99',
        image: '/assets/images/blueberry-cheesecake.jpg',
        description: 'This is a Blueberry cheesecake with a vanilla frosting.',
    },
    {
        id: 2,
        title: 'Chocolate Cake',
        category: 'Dessert',
        price: '$5.00',
        image: '/assets/images/chocolate-cake.jpg',
        description: 'This is a chocolate cake with a vanilla frosting.',
    },
    {
        id: 3,
        title: 'Spring Roll',
        category: 'Appetizer',
        price: '$1.99',
        image: '/assets/images/spring-roll.jpg',
        description: 'This is a spring roll with a spring onion.',
    },
    {
        id: 4,
        title: 'Mozzarella Sticks',
        category: 'Appetizer',
        price: '$2.99',
        image: '/assets/images/cheese-sticks.jpg',
        description: 'This is a mozzarella sticks with a spring onion.',
    },
    {
        id: 5,
        title: 'Pizza',
        category: 'Dinner',
        price: '$5.99',
        image: '/assets/images/pizza.jpg',
        description: 'This pizza you can add up to 5 toppings.',
    },
    {
        id: 6,
        title: 'Eggplant Parmesan',
        category: 'Dinner',
        price: '$6.99',
        image: '/assets/images/eggplant-parmesan.jpg',
        description:
            'A delicious eggplant parmesan with a suberb tomato souce and amazing cheese.',
    },
    {
        id: 7,
        title: 'Banana Pancakes',
        category: 'Breakfast',
        price: '$3.99',
        image: '/assets/images/banana-pancakes.jpg',
        description: 'This is a banana pancakes with a banana buttercream.',
    },
    {
        id: 8,
        title: 'Toasted English Muffins',
        category: 'Breakfast',
        price: '$2.99',
        image: '/assets/images/english-muffins.jpg',
        description:
            'This is a toasted english muffins with a banana buttercream.',
    },
    {
        id: 9,
        title: 'French Toast',
        category: 'Breakfast',
        price: '$3.99',
        image: '/assets/images/french-toast.jpg',
        description: 'This is French toast with a banana buttercream.',
    },
    {
        id: 10,
        title: 'Clover Salad',
        category: 'Salad',
        price: '$5.99',
        image: '/assets/images/clover-salad.jpg',
        description: 'This is a clover salad with an amazing dresssing.',
    },
    {
        id: 11,
        title: 'Spring Salad',
        category: 'Salad',
        price: '$6.99',
        image: '/assets/images/spring-salad.jpg',
        description: 'This is a Spring salad with an amazing dresssing.',
    },
    {
        id: 12,
        title: 'Bacon Burger',
        category: 'Lunch',
        price: '$5.99',
        image: '/assets/images/bacon-burger.jpg',
        description: 'This is a bacon burger with an lots of cheese.',
    },
    {
        id: 13,
        title: 'Salmon Burger Special',
        category: 'Lunch',
        price: '$6.99',
        image: '/assets/images/salmon-burger-special.jpg',
        description: 'This is a Salmon burger with an lots of cheese.',
    },
]
