const LOREMDATA = [
    'Lorem ipsum dolor sit amet. Qui enim nemo et enim consequuntur eos consequatur odio. Et voluptatem dolores aut itaque aliquid eos laudantium sunt et tenetur rerum aut omnis quidem et porro rerum eum facilis delectus. Sed minus vero qui consequatur expedita et omnis tempora.',
    'Rem saepe soluta ea expedita autem qui quasi dolorem qui minima voluptate sed fugit adipisci aut tenetur necessitatibus. Hic accusantium nulla id dolores veritatis ea reprehenderit numquam sed voluptate quasi. Et ratione maxime sed rerum provident sed veritatis fuga.',
    'Vel molestiae velit id laboriosam quia a reiciendis cupiditate non aperiam minus et tenetur illum. Qui quis vitae et tempora nihil eos officiis saepe et necessitatibus nobis qui autem tempora. Est consequuntur sapiente quo commodi enim sed voluptatibus voluptatem hic dolor architecto eos incidunt eligendi ab iusto necessitatibus. Est dolorem internos aut repellat officia rem necessitatibus nobis.',
    'Ea aspernatur aspernatur a modi tempore vel dolor sequi eum sunt sapiente aut rerum omnis At modi aperiam aut facere libero. Rem dolores molestiae aut eaque magni ea voluptates beatae sed dignissimos deserunt non doloremque pariatur ea dolores galisum. Et voluptates ipsam eos quaerat animi aut assumenda galisum quo dolorum praesentium qui sapiente deleniti ea veritatis dolorem rem sequi nihil.',
    'Est magni possimus a quibusdam possimus nam sunt obcaecati aut deleniti enim. Est dignissimos alias et sint nesciunt ut voluptas eligendi. Et eius consequatur et doloribus delectus in internos natus. Sit neque beatae cum dolorem vero non veniam unde et sapiente illum.',
    'Qui facilis odit in dolor ipsum At temporibus molestiae sed molestiae consequatur qui officia rerum qui asperiores ipsam. Aut galisum repellendus qui distinctio sapiente id voluptatibus labore est unde voluptatibus a dolorem voluptatem ea porro galisum? Aut voluptatem consequatur sed corrupti quaerat est delectus commodi et accusamus itaque. Aut quibusdam suscipit nam possimus voluptas aut voluptatum inventore quo reprehenderit quos.',
    'Hic deserunt quia aut sunt quasi sit asperiores nihil. Ut consequatur illum et dignissimos voluptatem et harum sapiente hic enim laboriosam. Et repellat ullam qui inventore omnis ut reiciendis obcaecati nam doloremque rerum et blanditiis voluptates aut accusantium facere qui quaerat iusto. Et voluptatem Quis non nisi fugit ut temporibus dolore qui dignissimos dolorem.',
    'Id repellat nostrum et doloribus iure sed pariatur aperiam consequatur odit aut consequuntur omnis? Eum esse mollitia ut vero excepturi ab dolores omnis aut repudiandae vitae qui galisum vero qui vero enim eum enim omnis?',
    'Ad provident alias quo dignissimos voluptas At quod alias et fuga facere. Est quasi tempore et tenetur dicta a voluptatum sapiente.',
    'Et culpa cumque aut animi perspiciatis ex expedita adipisci qui consequuntur consectetur? Non consequuntur pariatur aut dicta galisum qui vero voluptatum ut aspernatur dolor.',
    'Vel velit iste hic temporibus dolorem et similique eveniet ut esse ipsa aut iure autem. Aut nesciunt dolor eos distinctio nulla ut accusantium omnis nam nesciunt voluptatem sed voluptatibus repudiandae ut quaerat itaque.',
    'Ut molestias voluptas eum nesciunt mollitia et exercitationem tenetur qui recusandae aspernatur aut odit similique ut provident amet! Ut voluptatem perspiciatis ex quisquam velit et exercitationem sint id consequuntur nemo nam commodi libero aut voluptatibus autem et rerum sunt.',
    'Aut beatae pariatur ut voluptatem inventore est soluta possimus nam exercitationem molestiae? Ut culpa placeat et libero placeat sit aspernatur dolorem. Est iste aperiam quo mollitia internos et quidem aliquid.',
    'Ut earum distinctio et optio deleniti quo molestiae praesentium et labore quae eos deleniti dolorem et sint accusantium. Aliquid laborum eos asperiores earum est neque iste sed optio explicabo aut distinctio eligendi ex vitae delectus. Et quisquam cumque aut voluptas rerum ad fuga vero! Hic voluptatem ratione est officia vitae et provident officia qui neque est aperiam perferendis.',
    'Non Quis necessitatibus et veritatis aspernatur id nemo accusantium aut aspernatur galisum et nemo facilis ut fuga quae. Est sint quasi eum quaerat maiores ut ipsum quod id voluptas nostrum ea voluptas voluptatem 33 dolorem voluptatem? Et dolorem consequuntur eum voluptatem quae ut deleniti perspiciatis delectus consectetur in ducimus perspiciatis sed voluptates inventore ut iste ducimus.',
    'Vel exercitationem omnis vel voluptatibus omnis ut quidem deleniti aut distinctio enim aut nostrum itaque. Eos aspernatur suscipit qui facilis non laboriosam nisi aut amet voluptas 33 quae placeat est illum optio.',
    'Vel animi omnis et rerum dolores est officiis consequatur sed laudantium atque aut nobis ducimus a voluptas praesentium sit deleniti quis? Aut veniam voluptas est reiciendis eius aut minus sequi in maiores ducimus sit voluptatem velit non omnis amet provident doloribus.',
    'Sit consequuntur assumenda ut quas repellat aut exercitationem quae cum dolorum eaque aut repudiandae culpa et doloremque voluptas cum quae deleniti? Et veritatis deserunt ut quae temporibus cum delectus enim non iure mollitia?',
    'Vel vero quibusdam est dolorem soluta id delectus odio qui mollitia dolorem est fugit voluptates sit eius internos. Sed vero consectetur sit necessitatibus minima ut perferendis minima aut cumque facilis. Eos officiis odio et error incidunt saepe inventore.',
    'Et sapiente magnam ut amet mollitia eos sunt suscipit est mollitia omnis ad internos repudiandae qui ipsum officiis est tempora dolorum. Quo veritatis velit est quae harum a laboriosam tenetur quo dolor laborum eum rerum voluptatibus.',
]

//     {
//         id: 2,
//         name: 'words',
//         description: [
//             'Lorem',
//             'ipsum',
//             'dolor',
//             'sit',
//             'amet',
//             'consectetur,',
//             'adipisicing',
//             'elit.',
//             'Quas,',
//             'molestiae',
//             'ex!',
//             'Iste',
//             'nobis',
//             'possimus',
//             'voluptates',
//             'id',
//             'inventore',
//             'et',
//             'veniam,',
//             'aut,',
//             'similique',
//             'quibusdam',
//             'eius',
//             'eos',
//             'officiis',
//             'animi',
//             'atque.',
//             'Recusandae',
//             'aspernatur',
//             'quaerat',
//             'ipsam',
//             'facere',
//             'iure',
//             'fugit',
//             'veritatis!',
//             'Explicabo',
//             'adipisci',
//             'odio',
//             'cupiditate',
//             'exercitationem',
//             'repellat',
//             'numquam',
//             'officia',
//             'recusandae',
//             'at',
//             'enim',
//             'optio',
//             'nisi',
//             'soluta',
//             'a',
//             'tempora,',
//             'vitae',
//             'aspernatur',
//             'quasi',
//             'assumenda.',
//             'Illum',
//             'enim,',
//             'tempore',
//             'dolor',
//             'repellat',
//             'id',
//             'asperiores',
//             'quis',
//             'blanditiis',
//             'beatae',
//             'assumenda',
//             'lororemque',
//             'reiciendis',
//             'temporibus',
//             'eius',
//             'vitae',
//             'eos',
//             'tempora',
//             'dicta',
//             'voluptatibus',
//             'quae.',
//             'Ullam',
//             'quas,',
//             'asperiores',
//             'officia',
//             'eum',
//             'quisquam,',
//             'numquam',
//             'dolore',
//             'vel',
//             'inventore',
//             'officiis',
//             'accusamus',
//             'quae',
//             'consectetur',
//             'minus',
//             'alias',
//             'tenetur',
//             'aspernatur',
//             'delectus',
//             'repellat!',
//             'Necessitatibus',
//             'ab',
//             'exercitationem',
//             'molestiae!',
//         ],
//     },
// ]

export default LOREMDATA
