export const theme = {
    fonts: {
        primary: 'Rajdhani, sans-serif',
        secondary: 'Teko, sans-serif',
        terciary: 'Bangers, cursive',
    },
    colors: {
        green: '#A9ED33',
        lightgreen: '#E1FADA',
        darkgreen: '#00A851',
        darkblue: '#22508C',
        blue: '#60C2FB',
        lightblue: '#BFE6F7',
        turquise: '#7AEEDB',
        orange: '#FF8E25',
        red: '#FF5252',
        pink: '#FF4081',
        purple: '#9C27B0',
        white: '#FFFFFF',
        black: '#000000',
        gray: '#696969',
        lightgray: '#B0B0B0',
        darkBlue: '#2C3E50',
        darkGray: '#2B2A2A',
        darkRed: '#862D2B',
        darkPink: '#9D1A4A',
        darkPurple: '#4A1A58',
        darkGreen: '#1B5E20',
        darkOrange: '#8C4D17',
        yellow: '#FFE415',
        aguablue: '#B5F9E5',
        darkGray3: '#616161',
        darkGray4: '#424242',

        primaryBG: '#D0D6D0FB',
    },
    breakpoints: {
        mobile: '576px',
        tablet: '768px',
        laptop: '992px',
        desktop: '1280px',
    },
    fontSizes: {
        xxsmall: '0.5rem',
        xsmall: '0.75rem',
        small: '1rem',
        medium: '1.3rem',
        large: '1.7rem',
        xlarge: '2rem',
        xxlarge: '2.5rem',
        xxxlarge: '3rem',
    },
}
